class ConfObject:
    def __init__(self, apiKey,apiSecret,exchangeId,symbol,quote,confName,indicator,subaccount,timeFrame,periot,supertrendPeriod,supertrendFactor,t3Period,t3Volume,repeatSecond,test,appendSubData,subTimeFrame,showGraph,):
        self.apiKey = apiKey
        self.apiSecret = apiSecret
        self.exchangeId = exchangeId
        self.symbol = symbol
        self.quote = quote
        self.confName = confName
        self.indicator = indicator
        self.subaccount = subaccount
        self.timeFrame = timeFrame
        self.periot = periot
        self.supertrendPeriod = supertrendPeriod
        self.supertrendFactor = supertrendFactor
        self.t3Period = t3Period
        self.t3Volume = t3Volume
        self.repeatSecond = repeatSecond
        self.test = test
        self.appendSubData = appendSubData
        self.subTimeFrame = subTimeFrame
        self.showGraph = showGraph